### ISSUE TITLE
Could you consider adding a file mode for this utility

### ISSUE THREAD

**Issue by i30817** [pbatard/ms-sys#1]
I ran this on a loopback mount from udisksctl, but it required sudo to run (i thought because it was a system loopback not a fuse filesystem).

Now just for the heck of it, i tried to provide a file to see if it works, and i'm getting errors like:
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied

and it could not stat device for the file i gave. So two questions:

ms-sys requires root or is this a effect of me not using a fuse loop filesystem (which none are packaged sadly)?
could you consider a mode which operates on files to complement parted not requiring a device?

**Comment by pbatard** [comment]
Sorry but I am not the maintainer of this project. This is a straight mirror of the __original__ project found at : http://ms-sys.sourceforge.net/.

Please log an issue there.
